### ISSUE TITLE
Fail to build cisst-ros with catkin build on Ubuntu 16.04 (cannot find mtsDelayedConnections.h)

### ISSUE THREAD

**Issue by chenjq20** [jhu-cisst/cisst#83]
Hello, I built dVRK with Ubuntu 16.04, kinetic 1.12.13 and Cmake 3.5.1. I have already created the workspace with packages named "cisst-saw", "crtk", "dvrk-gravity-compensation", "dvrk-ros" and "irob-saf". 

When I built this workspace with catkin build, I got this error:

`~/catkin_ws/src/cisst-saw/cisst-ros/cisst_ros_crtk/include/cisst_ros_crtk/mts_ros_crtk_bridge.h:26:50: fatal error: cisstMultiTask/mtsDelayedConnections.h: No such file or directory`

And I cannot find this file elsewhere. This led to the failure of the complilation of cisst_ros_crtk and the abandon of dvrk_robot.

How can I find this cisstMultiTask/mtsDelayedConnections.h file or how can I build without it? Thank you very much!

**Comment by adeguet1** [comment]
This file has recently been introduced and can be found in the devel branch.

---

On Feb 8, 2021, at 10:04 PM, chenjq20 <notifications@github.com> wrote:

﻿

Hello, I built dVRK with Ubuntu 16.04, kinetic 1.12.13 and Cmake 3.5.1. I have already created the workspace with packages named "cisst-saw", "crtk", "dvrk-gravity-compensation", "dvrk-ros" and "irob-saf".

When I built this workspace with catkin build, I got this error:

~/catkin_ws/src/cisst-saw/cisst-ros/cisst_ros_crtk/include/cisst_ros_crtk/mts_ros_crtk_bridge.h:26:50: fatal error: cisstMultiTask/mtsDelayedConnections.h: No such file or directory

And I cannot find this file elsewhere. This led to the failure of the complilation of cisst_ros_crtk and the abandon of dvrk_robot.

How can I find this cisstMultiTask/mtsDelayedConnections.h file or how can I build without it? Thank you very much!

**Comment by adeguet1** [comment]
This issue is likely due to a mismatch of branches between repositories.   Until we release the next versions to the master branches you can use wstool to make sure you have the correct branches for each repository.  The wstool/rosinstall file for the development code can be found here: https://github.com/jhu-dvrk/dvrk-ros/blob/devel/dvrk_ros.rosinstall

---

On Feb 9, 2021, at 6:33 AM, Anton Deguet <anton.deguet@jhu.edu> wrote:

﻿ This file has recently been introduced and can be found in the devel branch.

---

On Feb 8, 2021, at 10:04 PM, chenjq20 <notifications@github.com> wrote:

﻿

Hello, I built dVRK with Ubuntu 16.04, kinetic 1.12.13 and Cmake 3.5.1. I have already created the workspace with packages named "cisst-saw", "crtk", "dvrk-gravity-compensation", "dvrk-ros" and "irob-saf".

When I built this workspace with catkin build, I got this error:

~/catkin_ws/src/cisst-saw/cisst-ros/cisst_ros_crtk/include/cisst_ros_crtk/mts_ros_crtk_bridge.h:26:50: fatal error: cisstMultiTask/mtsDelayedConnections.h: No such file or directory

And I cannot find this file elsewhere. This led to the failure of the complilation of cisst_ros_crtk and the abandon of dvrk_robot.

How can I find this cisstMultiTask/mtsDelayedConnections.h file or how can I build without it? Thank you very much!

**Comment by chenjq20** [comment]
Thank you very much for your kind help! I have solved this problem by getting the correct branches for each repository as you suggested. These suggestions are very helpful.
