### ISSUE TITLE
Failed to compile on Ubuntu 20.04

### ISSUE THREAD

**Issue by nicolapiccinelli** [jhu-cisst/cisst#123]
Hello @adeguet1 I'm trying to compile the latest `cisst` version (on main) on Ubuntu 20.04. I don't know if the platform is still supported by the project, but there are a few compilation issues:

- Inside the CMake file `cisst/cisst-dependencies/CMakeLists.txt`, this line fails, the CMake variable is not available:
`cisst_set_package_settings (cisstGraphviz GRAPHVIZ LINK_DIRECTORIES    GRAPHVIZ_LIBRARY_DIRS)`

- Inside the file `cisst/cisstMultiTask/mstComponentViewerQt.h`, there is a missing include:
`#include<memory>`

- The `cisstQtNodes` library is pointing to an external Qt library, which requires Qt > 5.15. On Ubuntu 20.04, the Qt version is 5.12.8, and the linker throws the following error: 
```
cisstQtNodes/lib/libQtNodes.so: undefined reference to `QtNodes::staticMetaObject'
```

The platform details are:

```
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by adeguet1** [comment]
Can you try `apt install libgraphviz-dev`?  I assume this package is available on 20.04.  This might be the simplest fix for now.  On the long run, the option CISST_HAS_QTNODES needs to be cached so users can turn this off.  I believe @brendanburkhart already ran into that issue :-)

**Comment by nicolapiccinelli** [comment]
I've already installed `libgraphviz-dev`, the issue is only related to **GRAPHVIZ_LIBRARY_DIRS**. The other two variables are recognised by CMake.

**Comment by adeguet1** [comment]
I changed the default behavior so CISST_HAS_QTNODES is turned off if graphviz is not found.  I will try to locate a machine with 20.04 to test this.
